import type { Deal, User } from '../../types'
import { resolveAssetPath } from '../../utils/assets'
import { readStorage, writeStorage } from './storage'

const SEED_VERSION = 4

const seedDeals: Deal[] = [
	{
		id: 'deal_korzinka_1',
		brand: 'Korzinka',
		category: 'Food & Drink',
		title: '15% off weekly essentials',
		description: 'Student bundles on fresh produce and snacks.',
		terms: 'Valid in-store and online. One use per week.',
		code: 'TALABA15',
		expiresAt: '2026-06-30',
		verifiedOnly: true,
		featured: true,
		createdAt: '2025-11-12',
		redemptionUrl: 'https://korzinka.uz',
		image: '/brands/korzinka.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_korzinka_2',
		brand: 'Korzinka',
		category: 'Food & Drink',
		title: '10,000 UZS off orders over 80,000',
		description: 'Fill your cart with essentials and save.',
		terms: 'Online orders only. Minimum spend 80,000 UZS.',
		code: 'KORZINKA10',
		expiresAt: '2026-04-10',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-10-02',
		redemptionUrl: 'https://korzinka.uz',
		image: '/brands/korzinka.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_makro_1',
		brand: 'Makro',
		category: 'Food & Drink',
		title: '20% off ready meals',
		description: 'Quick meals for finals week.',
		terms: 'Valid after 6pm. Participating stores only.',
		code: 'MAKRO20',
		expiresAt: '2026-03-15',
		verifiedOnly: false,
		featured: true,
		createdAt: '2025-12-01',
		image: '/brands/havas.jpg',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_makro_2',
		brand: 'Makro',
		category: 'Food & Drink',
		title: '5% off pantry staples',
		description: 'Stock up on student essentials.',
		terms: 'Valid on select items. One use per day.',
		code: 'MAKRO5',
		expiresAt: '2026-05-20',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-14',
		image: '/brands/havas.jpg',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_havas_1',
		brand: 'Havas',
		category: 'Food & Drink',
		title: '12% off bakery picks',
		description: 'Grab fresh pastries with a student discount.',
		terms: 'Morning hours only. Excludes cakes.',
		code: 'HAVAS12',
		expiresAt: '2026-05-01',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-09-18',
		image: '/brands/havas.jpg',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_chopar_1',
		brand: 'Chopar Pizza',
		category: 'Food & Drink',
		title: 'Buy 1 get 1 student slice',
		description: 'Share a slice with your group.',
		terms: 'Dine-in only. Valid Mon-Thu.',
		code: 'CHOPARBOGO',
		expiresAt: '2026-02-28',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-11-20',
		image: '/brands/chopar.avif',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_chopar_2',
		brand: 'Chopar Pizza',
		category: 'Food & Drink',
		title: '20% off combo meal',
		description: 'Pizza + drink combo for less.',
		terms: 'Valid after 5pm. Limited to 2 combos.',
		code: 'CHOPAR20',
		expiresAt: '2026-04-12',
		verifiedOnly: false,
		featured: true,
		createdAt: '2026-01-18',
		image: '/brands/chopar.avif',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_basilic_1',
		brand: 'Basilic',
		category: 'Food & Drink',
		title: '18% off vegan bowls',
		description: 'Healthy fuel for study sessions.',
		terms: 'Online pickup only. Limited to 2 per day.',
		code: 'BASILIC18',
		expiresAt: '2026-07-05',
		verifiedOnly: false,
		featured: true,
		createdAt: '2026-01-05',
		image: '/brands/basilic.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_basilic_2',
		brand: 'Basilic',
		category: 'Food & Drink',
		title: 'Free smoothie upgrade',
		description: 'Boost your bowl with a smoothie.',
		terms: 'In-store only. One per visit.',
		code: 'BASILICUP',
		expiresAt: '2026-06-02',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-25',
		image: '/brands/basilic.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_safia_1',
		brand: 'Safia',
		category: 'Food & Drink',
		title: 'Free mini dessert with any drink',
		description: 'Pair your coffee with a sweet treat.',
		terms: 'In-store only. One per visit.',
		code: 'SAFIAFREE',
		expiresAt: '2026-04-25',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-08-30',
		image: '/brands/safia.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_safia_2',
		brand: 'Safia',
		category: 'Food & Drink',
		title: '15% off cakes',
		description: 'Sweet treats for study breaks.',
		terms: 'Excludes custom orders.',
		code: 'SAFIA15',
		expiresAt: '2026-05-28',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-01-12',
		image: '/brands/safia.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_beeline_1',
		brand: 'Beeline Uzbekistan',
		category: 'Telecom',
		title: '30% off monthly student data',
		description: 'Boost your data for streaming lectures.',
		terms: 'New student plan activations only.',
		code: 'BEE30',
		expiresAt: '2026-08-01',
		verifiedOnly: true,
		featured: true,
		createdAt: '2025-12-12',
		image: '/brands/beeline.jpg',
	},
	{
		id: 'deal_beeline_2',
		brand: 'Beeline Uzbekistan',
		category: 'Telecom',
		title: '10GB night data bonus',
		description: 'Late-night study streaming boost.',
		terms: 'Valid for student plans only.',
		code: 'BEE10GB',
		expiresAt: '2026-06-12',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-01-08',
		image: '/brands/beeline.jpg',
	},
	{
		id: 'deal_ucell_1',
		brand: 'Ucell',
		category: 'Telecom',
		title: '5GB bonus on top-up',
		description: 'Extra data for student plans.',
		terms: 'Valid once per month. Online top-ups.',
		code: 'UCELL5GB',
		expiresAt: '2026-03-20',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-09-12',
		image: '/brands/ucell.png',
	},
	{
		id: 'deal_ucell_2',
		brand: 'Ucell',
		category: 'Telecom',
		title: '20% off student roaming',
		description: 'Stay connected while traveling.',
		terms: 'Valid on select roaming packs.',
		code: 'UCELLROAM',
		expiresAt: '2026-07-02',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-01-10',
		image: '/brands/ucell.png',
	},
	{
		id: 'deal_mobiuz_1',
		brand: 'Mobiuz',
		category: 'Telecom',
		title: '20,000 UZS off annual plan',
		description: 'Save on a 12-month student plan.',
		terms: 'Online activation only.',
		code: 'MOBIUZ20',
		expiresAt: '2026-05-15',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-11-04',
		image: '/brands/mobi.webp',
	},
	{
		id: 'deal_mobiuz_2',
		brand: 'Mobiuz',
		category: 'Telecom',
		title: '15% off prepaid top-ups',
		description: 'Save every time you top up.',
		terms: 'Online top-ups only.',
		code: 'MOBI15',
		expiresAt: '2026-06-25',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-03',
		image: '/brands/mobi.webp',
	},
	{
		id: 'deal_yandex_1',
		brand: 'Yandex Go (Uzbekistan)',
		category: 'Ride/Delivery',
		title: '25% off 3 rides',
		description: 'Ride to campus for less.',
		terms: 'Max discount 12,000 UZS per ride.',
		code: 'GO25',
		expiresAt: '2026-02-22',
		verifiedOnly: true,
		featured: true,
		createdAt: '2025-12-20',
		image: '/brands/yandex_go.png',
	},
	{
		id: 'deal_yandex_2',
		brand: 'Yandex Go (Uzbekistan)',
		category: 'Ride/Delivery',
		title: 'Free delivery on 2 orders',
		description: 'Food delivery perks for students.',
		terms: 'Valid on orders above 60,000 UZS.',
		code: 'GOFREE2',
		expiresAt: '2026-05-18',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-01-06',
		image: '/brands/yandex_go.png',
	},
	{
		id: 'deal_express24_1',
		brand: 'Express24',
		category: 'Ride/Delivery',
		title: '15,000 UZS off first delivery',
		description: 'Late night study snack unlocked.',
		terms: 'New users only.',
		code: 'EXPRESS15',
		expiresAt: '2026-01-30',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-10-18',
		image: '/brands/express24.jpg',
	},
	{
		id: 'deal_express24_2/',
		brand: 'Express24',
		category: 'Ride/Delivery',
		title: '10% off grocery delivery',
		description: 'Quick grocery runs for less.',
		terms: 'Min order 70,000 UZS.',
		code: 'EXPRESS10',
		expiresAt: '2026-05-22',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-09',
		image: '/brands/express24.jpg',
	},
	{
		id: 'deal_lc_1',
		brand: 'LC Waikiki Uzbekistan',
		category: 'Fashion',
		title: '20% off campus fits',
		description: 'Refresh your wardrobe for the new term.',
		terms: 'Valid in-store. Excludes accessories.',
		code: 'LC20',
		expiresAt: '2026-06-10',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-09-25',
		image: '/brands/lcwaikiki.png',
	},
	{
		id: 'deal_lc_2',
		brand: 'LC Waikiki Uzbekistan',
		category: 'Fashion',
		title: '15% off outerwear',
		description: 'Stay warm with student savings.',
		terms: 'Selected items only.',
		code: 'LC15',
		expiresAt: '2026-06-18',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-01-16',
		image: '/brands/lcwaikiki.png',
	},
	{
		id: 'deal_defacto_1',
		brand: 'DeFacto Uzbekistan',
		category: 'Fashion',
		title: '15% off denim edit',
		description: 'Classic denim with a student price.',
		terms: 'Online only.',
		code: 'DENIM15',
		expiresAt: '2026-03-30',
		verifiedOnly: false,
		featured: true,
		createdAt: '2025-11-15',
		image: '/brands/just.png',
	},
	{
		id: 'deal_defacto_2',
		brand: 'DeFacto Uzbekistan',
		category: 'Fashion',
		title: '10% off basics pack',
		description: 'Everyday essentials with student price.',
		terms: 'Online only.',
		code: 'BASIC10',
		expiresAt: '2026-05-14',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-04',
		image: '/brands/just.png',
	},
	{
		id: 'deal_asaxiy_1',
		brand: 'Asaxiy Books',
		category: 'Books & Education',
		title: 'Buy 2 get 1 academic title',
		description: 'Build your semester reading stack.',
		terms: 'Applies to selected textbooks.',
		code: 'ASAXIY321',
		expiresAt: '2026-07-15',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-10',
		image: '/brands/asaxiy.png',
	},
	{
		id: 'deal_asaxiy_2',
		brand: 'Asaxiy Books',
		category: 'Books & Education',
		title: '20% off exam prep guides',
		description: 'Top titles for exam season.',
		terms: 'Selected guides only.',
		code: 'ASAXIY20',
		expiresAt: '2026-07-20',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-15',
		image: '/brands/asaxiy.png',
	},
	{
		id: 'deal_najot_1',
		brand: "Najot Ta'lim",
		category: 'Books & Education',
		title: '12% off bootcamp tuition',
		description: 'Upskill with verified student pricing.',
		terms: 'Valid for first-time enrollments.',
		code: 'NAJOT12',
		expiresAt: '2026-05-30',
		verifiedOnly: true,
		featured: true,
		createdAt: '2025-12-28',
		image: '/brands/najot_talim.png',
	},
	{
		id: 'deal_najot_2',
		brand: "Najot Ta'lim",
		category: 'Books & Education',
		title: 'Free career session',
		description: 'One-on-one student mentor call.',
		terms: 'New students only.',
		code: 'NAJOTFREE',
		expiresAt: '2026-06-10',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-01-07',
		image: '/brands/najot_talim.png',
	},
	{
		id: 'deal_ozone_1',
		brand: 'Ozone Fitness',
		category: 'Fitness',
		title: '1 month free on 6 month plan',
		description: 'Train smart with student pricing.',
		terms: 'New memberships only.',
		code: 'OZONE1FREE',
		expiresAt: '2026-04-05',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-10-25',
		image: '/brands/extreme_fitness.png',
	},
	{
		id: 'deal_ozone_2',
		brand: 'Ozone Fitness',
		category: 'Fitness',
		title: '20% off group classes',
		description: 'Join group training sessions.',
		terms: 'Valid weekdays only.',
		code: 'OZONE20',
		expiresAt: '2026-05-30',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-11',
		image: '/brands/extreme_fitness.png',
	},
	{
		id: 'deal_texnomart_1',
		brand: 'Texnomart',
		category: 'Electronics',
		title: '8% off laptops',
		description: 'Upgrade your study setup.',
		terms: 'Selected models only. Online checkout.',
		code: 'TEXNO8',
		expiresAt: '2026-06-20',
		verifiedOnly: true,
		featured: true,
		createdAt: '2026-01-02',
		image: '/brands/texnomart.png',
	},
	{
		id: 'deal_texnomart_2',
		brand: 'Texnomart',
		category: 'Electronics',
		title: '12% off tablets',
		description: 'Lightweight devices for class.',
		terms: 'Selected models only.',
		code: 'TEXNO12',
		expiresAt: '2026-07-01',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-01-21',
		image: '/brands/texnomart.png',
	},
	{
		id: 'deal_mediapark_1',
		brand: 'MediaPark',
		category: 'Electronics',
		title: '15% off headphones',
		description: 'Noise-cancel your study sessions.',
		terms: 'In-store only. Limited stock.',
		code: 'MPHEAD15',
		expiresAt: '2026-05-10',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-11-22',
		image: '/brands/mediapark.png',
	},
	{
		id: 'deal_mediapark_2',
		brand: 'MediaPark',
		category: 'Electronics',
		title: '10% off smart watches',
		description: 'Track your day with student pricing.',
		terms: 'Limited stock.',
		code: 'MPWATCH10',
		expiresAt: '2026-06-18',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-13',
		image: '/brands/mediapark.png',
	},
	{
		id: 'deal_uzairways_1',
		brand: 'Uzbekistan Airways',
		category: 'Travel',
		title: '10% off student weekend fares',
		description: 'Book your next quick getaway.',
		terms: 'Valid on select domestic routes.',
		code: 'FLY10',
		expiresAt: '2026-08-30',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-12-05',
		image: '/brands/uzbekistan airways.png',
	},
	{
		id: 'deal_uzairways_2',
		brand: 'Uzbekistan Airways',
		category: 'Travel',
		title: 'Student baggage upgrade',
		description: 'Extra 5kg on student fares.',
		terms: 'Domestic routes only.',
		code: 'BAG5',
		expiresAt: '2026-08-20',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-01-17',
		image: '/brands/uzbekistan airways.png',
	},
	{
		id: 'deal_korzinka_3',
		brand: 'Korzinka',
		category: 'Food & Drink',
		title: 'Student snack bundle - 12% off',
		description: 'Snacks + drinks combo for study nights.',
		terms: 'Available in select stores.',
		code: 'KZSNACK12',
		expiresAt: '2026-07-08',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-05',
		image: '/brands/korzinka.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_havas_2',
		brand: 'Havas',
		category: 'Food & Drink',
		title: 'Free coffee upgrade',
		description: 'Upgrade to large size on any coffee.',
		terms: 'Morning hours only.',
		code: 'HAVASCOF',
		expiresAt: '2026-06-18',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-02',
		image: '/brands/havas.jpg',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_beeline_3',
		brand: 'Beeline Uzbekistan',
		category: 'Telecom',
		title: 'Student SIM pack 50% off',
		description: 'Starter SIM kit for new students.',
		terms: 'New activations only.',
		code: 'BEE50SIM',
		expiresAt: '2026-07-14',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-01',
		image: '/brands/beeline.jpg',
	},
	{
		id: 'deal_ucell_3',
		brand: 'Ucell',
		category: 'Telecom',
		title: 'Free 2GB weekend data',
		description: 'Bonus data for weekend streaming.',
		terms: 'Valid on student plans.',
		code: 'UCELL2GB',
		expiresAt: '2026-06-28',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-03',
		image: '/brands/ucell.png',
	},
	{
		id: 'deal_mobiuz_3',
		brand: 'Mobiuz',
		category: 'Telecom',
		title: 'Student SMS pack 30% off',
		description: 'Affordable messaging bundle.',
		terms: 'One per month.',
		code: 'MOBISMS30',
		expiresAt: '2026-06-30',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-02-04',
		image: '/brands/mobi.webp',
	},
	{
		id: 'deal_yandex_3',
		brand: 'Yandex Go (Uzbekistan)',
		category: 'Ride/Delivery',
		title: '15% off scooter rides',
		description: 'Fast campus rides with student pricing.',
		terms: 'Valid in select zones.',
		code: 'SCOOT15',
		expiresAt: '2026-06-25',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-02',
		image: '/brands/yandex_go.png',
	},
	{
		id: 'deal_express24_3',
		brand: 'Express24',
		category: 'Ride/Delivery',
		title: 'Free delivery after 9pm',
		description: 'Late-night study fuel.',
		terms: 'Participating restaurants only.',
		code: 'NIGHTFREE',
		expiresAt: '2026-06-08',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-02-06',
		image: '/brands/express24.jpg',
	},
	{
		id: 'deal_lc_3',
		brand: 'LC Waikiki Uzbekistan',
		category: 'Fashion',
		title: '10% off accessories',
		description: 'Bags, hats, and more.',
		terms: 'In-store only.',
		code: 'LCACC10',
		expiresAt: '2026-07-02',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-05',
		image: '/brands/lcwaikiki.png',
	},
	{
		id: 'deal_defacto_3',
		brand: 'DeFacto Uzbekistan',
		category: 'Fashion',
		title: '2-for-1 socks pack',
		description: 'Everyday essentials for students.',
		terms: 'Selected packs only.',
		code: 'SOCKS2',
		expiresAt: '2026-06-05',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-03',
		image: '/brands/just.png',
	},
	{
		id: 'deal_asaxiy_3',
		brand: 'Asaxiy Books',
		category: 'Books & Education',
		title: '15% off fiction bundle',
		description: 'Relax with curated fiction picks.',
		terms: 'Selected titles only.',
		code: 'ASAXIY15',
		expiresAt: '2026-08-01',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-01',
		image: '/brands/asaxiy.png',
	},
	{
		id: 'deal_najot_3',
		brand: "Najot Ta'lim",
		category: 'Books & Education',
		title: '10% off design course',
		description: 'Creative skills for students.',
		terms: 'Online courses only.',
		code: 'NAJOT10',
		expiresAt: '2026-07-10',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-02-04',
		image: '/brands/najot_talim.png',
	},
	{
		id: 'deal_ozone_3',
		brand: 'Ozone Fitness',
		category: 'Fitness',
		title: 'Student yoga pass 25% off',
		description: 'Weekly yoga sessions.',
		terms: 'Morning classes only.',
		code: 'OZONEYOGA',
		expiresAt: '2026-06-15',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-02',
		image: '/brands/extreme_fitness.png',
	},
	{
		id: 'deal_texnomart_3',
		brand: 'Texnomart',
		category: 'Electronics',
		title: '5% off chargers',
		description: 'Keep devices powered all day.',
		terms: 'Selected accessories only.',
		code: 'TEXNO5',
		expiresAt: '2026-06-22',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-05',
		image: '/brands/texnomart.png',
	},
	{
		id: 'deal_mediapark_3',
		brand: 'MediaPark',
		category: 'Electronics',
		title: '18% off speakers',
		description: 'Dorm room sound upgrade.',
		terms: 'Limited stock.',
		code: 'MPSPEAK18',
		expiresAt: '2026-07-03',
		verifiedOnly: true,
		featured: false,
		createdAt: '2026-02-01',
		image: '/brands/mediapark.png',
	},
	{
		id: 'deal_uzairways_3',
		brand: 'Uzbekistan Airways',
		category: 'Travel',
		title: 'Student lounge access 20% off',
		description: 'Relax before flights.',
		terms: 'Tashkent airport only.',
		code: 'LOUNGE20',
		expiresAt: '2026-08-10',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-02-02',
		image: '/brands/uzbekistan airways.png',
	},
]

const seedUsers: User[] = [
	{
		id: 'user_verified_1',
		email: "b.to'ymurodov@student.inha.uz",
		password: 'Talaba123!',
		firstName: 'Behruz',
		lastName: "To'ymurodov",
		username: 'behruz.toymurodov',
		age: 20,
		universityName: 'INHA University in Tashkent',
		role: 'student_verified',
		createdAt: '2025-09-01',
		verificationStatus: 'verified',
		verification: {
			studentEmail: "b.to'ymurodov@student.inha.uz",
			universityName: 'INHA University in Tashkent',
			studentId: 'U2310268',
			status: 'verified',
			submittedAt: '2025-09-02',
			reviewedAt: '2025-09-03',
		},
		savedDealIds: ['deal_korzinka_1', 'deal_yandex_1'],
	},
	{
		id: 'user_unverified_1',
		email: 'student@uni.uz',
		password: 'Talaba123!',
		firstName: 'Dilnoza',
		lastName: 'Rustamova',
		username: 'dilnoza.r',
		age: 19,
		universityName: 'National University of Uzbekistan',
		role: 'student_unverified',
		createdAt: '2025-10-11',
		verificationStatus: 'unverified',
		savedDealIds: [],
	},
	{
		id: 'user_admin_1',
		email: 'admin@talabahub.uz',
		password: 'Admin123!',
		firstName: 'Admin',
		lastName: 'User',
		username: 'admin',
		age: 28,
		universityName: 'INHA University in Tashkent',
		role: 'admin',
		createdAt: '2025-08-20',
		verificationStatus: 'verified',
		savedDealIds: [],
	},
]

export function ensureSeedData() {
	const users = readStorage<User[]>('users', [])
	const deals = readStorage<Deal[]>('deals', [])
	const seedVersion = readStorage<number>('seedVersion', 0)

	const normalizeDeal = (deal: Deal) => {
		const normalizedLogo = resolveAssetPath(deal.image, 'brands')
		const normalizedBanner = resolveAssetPath(deal.bannerImage, 'banners')
		return {
			...deal,
			image: normalizedLogo ?? deal.image,
			bannerImage:
				normalizedBanner ??
				(deal.category === 'Food & Drink'
					? '/banners/food.avif'
					: deal.bannerImage),
		}
	}

	if (users.length === 0) {
		writeStorage('users', seedUsers)
	}

	if (deals.length === 0) {
		writeStorage('deals', seedDeals.map(normalizeDeal))
		writeStorage('seedVersion', SEED_VERSION)
		return
	}

	if (seedVersion < SEED_VERSION) {
		const migrated = deals.map(normalizeDeal)
		writeStorage('deals', migrated)
		writeStorage('seedVersion', SEED_VERSION)
	}
}
