import type { Deal, User } from '../../types'
import { readStorage, writeStorage } from './storage'
import { resolveAssetPath } from '../../utils/assets'

const SEED_VERSION = 2

const seedDeals: Deal[] = [
	{
		id: 'deal_korzinka_1',
		brand: 'Korzinka',
		category: 'Food & Drink',
		title: '15% off weekly essentials',
		description: 'Student bundles on fresh produce and snacks.',
		terms: 'Valid in-store and online. One use per week.',
		code: 'TALABA15',
		expiresAt: '2026-06-30',
		verifiedOnly: true,
		featured: true,
		createdAt: '2025-11-12',
		redemptionUrl: 'https://korzinka.uz',
		image: '/brands/korzinka.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_korzinka_2',
		brand: 'Korzinka',
		category: 'Food & Drink',
		title: '10,000 UZS off orders over 80,000',
		description: 'Fill your cart with essentials and save.',
		terms: 'Online orders only. Minimum spend 80,000 UZS.',
		code: 'KORZINKA10',
		expiresAt: '2026-04-10',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-10-02',
		redemptionUrl: 'https://korzinka.uz',
		image: '/brands/korzinka.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_makro_1',
		brand: 'Makro',
		category: 'Food & Drink',
		title: '20% off ready meals',
		description: 'Quick meals for finals week.',
		terms: 'Valid after 6pm. Participating stores only.',
		code: 'MAKRO20',
		expiresAt: '2026-03-15',
		verifiedOnly: false,
		featured: true,
		createdAt: '2025-12-01',
		image: '/brands/havas.jpg',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_havas_1',
		brand: 'Havas',
		category: 'Food & Drink',
		title: '12% off bakery picks',
		description: 'Grab fresh pastries with a student discount.',
		terms: 'Morning hours only. Excludes cakes.',
		code: 'HAVAS12',
		expiresAt: '2026-05-01',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-09-18',
		image: '/brands/havas.jpg',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_chopar_1',
		brand: 'Chopar Pizza',
		category: 'Food & Drink',
		title: 'Buy 1 get 1 student slice',
		description: 'Share a slice with your group.',
		terms: 'Dine-in only. Valid Mon-Thu.',
		code: 'CHOPARBOGO',
		expiresAt: '2026-02-28',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-11-20',
		image: '/brands/chopar.avif',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_basilic_1',
		brand: 'Basilic',
		category: 'Food & Drink',
		title: '18% off vegan bowls',
		description: 'Healthy fuel for study sessions.',
		terms: 'Online pickup only. Limited to 2 per day.',
		code: 'BASILIC18',
		expiresAt: '2026-07-05',
		verifiedOnly: false,
		featured: true,
		createdAt: '2026-01-05',
		image: '/brands/basilic.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_safia_1',
		brand: 'Safia',
		category: 'Food & Drink',
		title: 'Free mini dessert with any drink',
		description: 'Pair your coffee with a sweet treat.',
		terms: 'In-store only. One per visit.',
		code: 'SAFIAFREE',
		expiresAt: '2026-04-25',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-08-30',
		image: '/brands/safia.png',
		bannerImage: '/banners/food.avif',
	},
	{
		id: 'deal_beeline_1',
		brand: 'Beeline Uzbekistan',
		category: 'Telecom',
		title: '30% off monthly student data',
		description: 'Boost your data for streaming lectures.',
		terms: 'New student plan activations only.',
		code: 'BEE30',
		expiresAt: '2026-08-01',
		verifiedOnly: true,
		featured: true,
		createdAt: '2025-12-12',
		image: '/brands/beeline.jpg',
	},
	{
		id: 'deal_ucell_1',
		brand: 'Ucell',
		category: 'Telecom',
		title: '5GB bonus on top-up',
		description: 'Extra data for student plans.',
		terms: 'Valid once per month. Online top-ups.',
		code: 'UCELL5GB',
		expiresAt: '2026-03-20',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-09-12',
		image: '/brands/ucell.png',
	},
	{
		id: 'deal_mobiuz_1',
		brand: 'Mobiuz',
		category: 'Telecom',
		title: '20,000 UZS off annual plan',
		description: 'Save on a 12-month student plan.',
		terms: 'Online activation only.',
		code: 'MOBIUZ20',
		expiresAt: '2026-05-15',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-11-04',
		image: '/brands/mobi.webp',
	},
	{
		id: 'deal_yandex_1',
		brand: 'Yandex Go (Uzbekistan)',
		category: 'Ride/Delivery',
		title: '25% off 3 rides',
		description: 'Ride to campus for less.',
		terms: 'Max discount 12,000 UZS per ride.',
		code: 'GO25',
		expiresAt: '2026-02-22',
		verifiedOnly: true,
		featured: true,
		createdAt: '2025-12-20',
		image: '/brands/yandex_go.png',
	},
	{
		id: 'deal_express24_1',
		brand: 'Express24',
		category: 'Ride/Delivery',
		title: '15,000 UZS off first delivery',
		description: 'Late night study snack unlocked.',
		terms: 'New users only.',
		code: 'EXPRESS15',
		expiresAt: '2026-01-30',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-10-18',
		image: '/brands/express24.jpg',
	},
	{
		id: 'deal_lc_1',
		brand: 'LC Waikiki Uzbekistan',
		category: 'Fashion',
		title: '20% off campus fits',
		description: 'Refresh your wardrobe for the new term.',
		terms: 'Valid in-store. Excludes accessories.',
		code: 'LC20',
		expiresAt: '2026-06-10',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-09-25',
		image: '/brands/lcwaikiki.png',
	},
	{
		id: 'deal_defacto_1',
		brand: 'DeFacto Uzbekistan',
		category: 'Fashion',
		title: '15% off denim edit',
		description: 'Classic denim with a student price.',
		terms: 'Online only.',
		code: 'DENIM15',
		expiresAt: '2026-03-30',
		verifiedOnly: false,
		featured: true,
		createdAt: '2025-11-15',
		image: '/brands/just.png',
	},
	{
		id: 'deal_asaxiy_1',
		brand: 'Asaxiy Books',
		category: 'Books & Education',
		title: 'Buy 2 get 1 academic title',
		description: 'Build your semester reading stack.',
		terms: 'Applies to selected textbooks.',
		code: 'ASAXIY321',
		expiresAt: '2026-07-15',
		verifiedOnly: false,
		featured: false,
		createdAt: '2026-01-10',
		image: '/brands/asaxiy.png',
	},
	{
		id: 'deal_najot_1',
		brand: "Najot Ta'lim",
		category: 'Books & Education',
		title: '12% off bootcamp tuition',
		description: 'Upskill with verified student pricing.',
		terms: 'Valid for first-time enrollments.',
		code: 'NAJOT12',
		expiresAt: '2026-05-30',
		verifiedOnly: true,
		featured: true,
		createdAt: '2025-12-28',
		image: '/brands/najot_talim.png',
	},
	{
		id: 'deal_ozone_1',
		brand: 'Ozone Fitness',
		category: 'Fitness',
		title: '1 month free on 6 month plan',
		description: 'Train smart with student pricing.',
		terms: 'New memberships only.',
		code: 'OZONE1FREE',
		expiresAt: '2026-04-05',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-10-25',
		image: '/brands/extreme_fitness.png',
	},
	{
		id: 'deal_texnomart_1',
		brand: 'Texnomart',
		category: 'Electronics',
		title: '8% off laptops',
		description: 'Upgrade your study setup.',
		terms: 'Selected models only. Online checkout.',
		code: 'TEXNO8',
		expiresAt: '2026-06-20',
		verifiedOnly: true,
		featured: true,
		createdAt: '2026-01-02',
		image: '/brands/texnomart.png',
	},
	{
		id: 'deal_mediapark_1',
		brand: 'MediaPark',
		category: 'Electronics',
		title: '15% off headphones',
		description: 'Noise-cancel your study sessions.',
		terms: 'In-store only. Limited stock.',
		code: 'MPHEAD15',
		expiresAt: '2026-05-10',
		verifiedOnly: false,
		featured: false,
		createdAt: '2025-11-22',
		image: '/brands/mediapark.png',
	},
	{
		id: 'deal_uzairways_1',
		brand: 'Uzbekistan Airways',
		category: 'Travel',
		title: '10% off student weekend fares',
		description: 'Book your next quick getaway.',
		terms: 'Valid on select domestic routes.',
		code: 'FLY10',
		expiresAt: '2026-08-30',
		verifiedOnly: true,
		featured: false,
		createdAt: '2025-12-05',
		image: '/brands/uzbekistan airways.png',
	},
]

const seedUsers: User[] = [
	{
		id: 'user_verified_1',
		email: 'verified.student@uni.uz',
		password: 'Talaba123!',
		role: 'student_verified',
		createdAt: '2025-09-01',
		verificationStatus: 'verified',
		verification: {
			studentEmail: 'verified.student@uni.uz',
			universityName: 'Tashkent University of Information Technologies',
			studentId: 'TU123456',
			status: 'verified',
			submittedAt: '2025-09-02',
			reviewedAt: '2025-09-03',
		},
		savedDealIds: ['deal_korzinka_1', 'deal_yandex_1'],
	},
	{
		id: 'user_unverified_1',
		email: 'student@uni.uz',
		password: 'Talaba123!',
		role: 'student_unverified',
		createdAt: '2025-10-11',
		verificationStatus: 'unverified',
		savedDealIds: [],
	},
	{
		id: 'user_admin_1',
		email: 'admin@talabahub.uz',
		password: 'Admin123!',
		role: 'admin',
		createdAt: '2025-08-20',
		verificationStatus: 'verified',
		savedDealIds: [],
	},
]

export function ensureSeedData() {
	const users = readStorage<User[]>('users', [])
	const deals = readStorage<Deal[]>('deals', [])
	const seedVersion = readStorage<number>('seedVersion', 0)

	const normalizeDeal = (deal: Deal) => {
		const normalizedLogo = resolveAssetPath(deal.image, 'brands')
		const normalizedBanner = resolveAssetPath(deal.bannerImage, 'banners')
		return {
			...deal,
			image: normalizedLogo ?? deal.image,
			bannerImage:
				normalizedBanner ??
				(deal.category === 'Food & Drink' ? '/banners/food.avif' : deal.bannerImage),
		}
	}

	if (users.length === 0) {
		writeStorage('users', seedUsers)
	}

	if (deals.length === 0) {
		writeStorage('deals', seedDeals.map(normalizeDeal))
		writeStorage('seedVersion', SEED_VERSION)
		return
	}

	if (seedVersion < SEED_VERSION) {
		const migrated = deals.map(normalizeDeal)
		writeStorage('deals', migrated)
		writeStorage('seedVersion', SEED_VERSION)
	}
}
