export const brandStories: Record<string, string> = {
  "Korzinka": "Fresh essentials for fast student routines — Korzinka keeps your week stocked and your budget calm.",
  "Makro": "Big baskets, smart prices — Makro helps you stretch your student budget without skipping quality.",
  "Havas": "Start your day with warm bakery vibes — Havas keeps study breaks tasty and quick.",
  "Chopar Pizza": "Late-night slices and group hangs — Chopar Pizza keeps campus cravings covered.",
  "Basilic": "Clean ingredients, bold flavor — Basilic fuels your focus with smart student meals.",
  "Safia": "Sweet breaks, small wins — Safia makes your study pauses feel like rewards.",
  "Beeline Uzbekistan": "Stay connected for classes, chats, and content — Beeline powers your student life.",
  "Ucell": "Reliable signal, student-friendly plans — Ucell keeps you online wherever you study.",
  "Mobiuz": "Flexible plans for busy weeks — Mobiuz helps you manage data without stress.",
  "Yandex Go (Uzbekistan)": "From campus to home and everywhere in between — Yandex Go keeps you moving.",
  "Express24": "Quick deliveries for busy days — Express24 brings essentials to your door.",
  "LC Waikiki Uzbekistan": "New semester, new fits — LC Waikiki refreshes your campus style on a budget.",
  "DeFacto Uzbekistan": "Everyday basics that just work — DeFacto makes student style simple.",
  "Asaxiy Books": "From textbooks to leisure reads — Asaxiy Books keeps your shelf ready.",
  "Najot Ta'lim": "Level up your skills fast — Najot Ta'lim supports your career goals.",
  "Ozone Fitness": "Healthy routine, strong mindset — Ozone Fitness helps you stay consistent.",
  "Texnomart": "Upgrade your setup — Texnomart delivers student-friendly tech deals.",
  "MediaPark": "Smart gadgets for study and chill — MediaPark keeps your tech game strong.",
  "Uzbekistan Airways": "Weekend escapes made easy — Uzbekistan Airways keeps student travel affordable.",
};
